# Generated by Django 5.0.4 on 2024-05-04 10:54

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=100)),
                ('date', models.DateTimeField(default=datetime.datetime.now)),
                ('game_type', models.TextField(choices=[('IND', 'Individual Tournament'), ('PAIR', 'Pair Tournament')], max_length=4)),
                ('deals_in_round', models.IntegerField()),
                ('scorer_type', models.TextField(choices=[('CROSS_IMP', 'Imp Scorer'), ('MAX', 'Max Scorer')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Movement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.TextField(choices=[('IND', 'Individual Tournament'), ('PAIR', 'Pair Tournament')], max_length=4)),
                ('name', models.TextField(max_length=100)),
                ('players', models.IntegerField()),
                ('tables', models.IntegerField()),
                ('rounds', models.IntegerField()),
                ('path', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=10)),
                ('round', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vul', models.TextField(max_length=1)),
                ('deal_number', models.IntegerField()),
                ('dealer', models.TextField(max_length=1)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deals', to='api.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='movement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='games', to='api.movement'),
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=8, unique=True)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='players', to='api.game')),
            ],
        ),
        migrations.CreateModel(
            name='Pairing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_number', models.IntegerField()),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='api.game')),
                ('e', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='e_pairings', to='api.player')),
                ('n', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='n_pairings', to='api.player')),
                ('s', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='s_pairings', to='api.player')),
                ('w', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='w_pairings', to='api.player')),
                ('table_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='table', to='api.table')),
            ],
        ),
        migrations.CreateModel(
            name='Score',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract', models.TextField(blank=True, max_length=8, null=True)),
                ('by', models.TextField(blank=True, max_length=1, null=True)),
                ('score', models.IntegerField(blank=True, null=True)),
                ('result', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True)),
                ('deal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.deal')),
                ('pairing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scores', to='api.pairing')),
            ],
        ),
    ]
