# Generated by Django 5.0.4 on 2024-05-04 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_table_name_pairing_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='name',
            field=models.TextField(max_length=8),
        ),
    ]
