# Generated by Django 5.0.4 on 2024-05-21 21:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_game_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='scorer_type',
            new_name='scorer',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='players',
            new_name='n_players',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='rounds',
            new_name='n_rounds',
        ),
        migrations.RenameField(
            model_name='movement',
            old_name='tables',
            new_name='n_tables',
        ),
        migrations.RenameField(
            model_name='table',
            old_name='round',
            new_name='actual_round',
        ),
        migrations.RemoveField(
            model_name='game',
            name='game_type',
        ),
        migrations.RemoveField(
            model_name='pairing',
            name='game',
        ),
        migrations.RemoveField(
            model_name='table',
            name='name',
        ),
        migrations.AddField(
            model_name='score',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='pairings', to='api.game'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='table',
            name='game',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='api.game'),
            preserve_default=False,
        ),
    ]
